### ISSUE TITLE
Create Github proxy server

### ISSUE THREAD

**Issue by rwdaigle** [zeke/queriac#4]
From [tweet](https://twitter.com/zeke/status/583700315788062720):

> Stand up a CORS webservice that serves up all files in a github repo as a key-value JSON object

**Comment by rwdaigle** [comment]
@zeke are you thinking something like this?

```session
$ curl https://ghproxy.herokuapp.com/v1/zeke/queriac.json
```

```json
{
  ".gitingore": "full body of file...",
  "README.md": "full body of file..."
}
```

Where the file contents are part of the JSON response?

And what about directories, how are those handled?

**Comment by zeke** [comment]
Yep, that's what I'm picturing! But js files only, and no directories. Flat.

**Comment by zeke** [comment]
If you're building this thing in node, the npm-cdn codebase might be helpful: https://github.com/zeke/npm-cdn

The way I would do this is to pull down a repo tarball and extract it to `/tmp`, rather than futzing with the github API. But I'll take what I can get!

**Comment by rwdaigle** [comment]
:+1:

I'll see what I can do...

**Comment by rwdaigle** [comment]
@zeke how does this look?

```session
$ curl https://queriac-github-proxy.herokuapp.com/v1/zeke/queriac-commands
```

```json
{
  "_commands.js": "var basicCSV = ...",
  "a.js": "// Search Amazon\n\n/*\nSearches all of amazon.com\n*/\n\nlocation = \"http://www.amazon.com/s/ref=nb_sb_noss_2?field-keywords=\"+args.join(\" \")\n",
  "acr.js": "..."
}
```

Repo [here](https://github.com/rwdaigle/queriac-github-proxy)

**Comment by zeke** [comment]
:clap:

**Comment by rwdaigle** [comment]
@zeke it's very raw, so let me know when it starts to be limiting.
